//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica.Exception.Usuario {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clinica.Exception.Usuario.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email must be a valid email address..
        /// </summary>
        public static string THE_EMAIL_IS_INVALID {
            get {
                return ResourceManager.GetString("THE_EMAIL_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email is required..
        /// </summary>
        public static string THE_EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("THE_EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name is required..
        /// </summary>
        public static string THE_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("THE_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name must be at most 100 characters long..
        /// </summary>
        public static string THE_NAME_MAX_LENGTH_100 {
            get {
                return ResourceManager.GetString("THE_NAME_MAX_LENGTH_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password is required..
        /// </summary>
        public static string THE_PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("THE_PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must be at most 50 characters long..
        /// </summary>
        public static string THE_PASSWORD_MAX_LENGTH_50 {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MAX_LENGTH_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must be at least 6 characters long..
        /// </summary>
        public static string THE_PASSWORD_MIN_LENGTH_6 {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MIN_LENGTH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one lowercase letter..
        /// </summary>
        public static string THE_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one number..
        /// </summary>
        public static string THE_PASSWORD_MUST_CONTAIN_NUMBER {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MUST_CONTAIN_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one special symbol (! ? * . % @)..
        /// </summary>
        public static string THE_PASSWORD_MUST_CONTAIN_SPECIAL_SYMBOL {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MUST_CONTAIN_SPECIAL_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one uppercase letter..
        /// </summary>
        public static string THE_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER {
            get {
                return ResourceManager.GetString("THE_PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER", resourceCulture);
            }
        }
    }
}
